import "./globals.css";
import Header from "@/components/Header";
import Background from "@/components/Background";
import { Poppins } from "next/font/google";
const poppins = Poppins({ subsets: ["latin"], weight: "200" });

export const metadata = {
  title: "Shahadha - Tshirt | Punjabi",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`relative ${poppins.className} text-white`}>
        <Background />
        <Header />
        {children}
      </body>
    </html>
  );
}
