import "./globals.css";
import Header from "@/components/Header";
import Background from "@/components/Background";
import { Poppins } from "next/font/google";
import Footer from "@/components/Footer";
const poppins = Poppins({ subsets: ["latin"], weight: "200" });

export const metadata = {
  title: "Shahadha - Tshirt | Punjabi",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`relative ${poppins.className} text-white`}>
        <Background />
        <Header />
        {children}
        <footer className="mt-24 pb-2 px-5 lg:px-0">
          <Footer />
        </footer>
      </body>
    </html>
  );
}
