import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
import Background from "@/components/Background";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Shahadha - Tshirt | Punjabi",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`relative ${inter.className} text-white`}>
        <Background />
        <Header />
        {children}
      </body>
    </html>
  );
}
